name: auto-pr

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@aac84d1baab4f1b9d062401cde1b7e9a7dde1a2e # feat/T0003
