name: auto-pr

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@e4a5a01bc3bbcb81f503f3310ffb1bec0e8cfd4a # feat/T0003
