name: auto-pr

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@20d34b1365502b8d4b4a3fe2d1aa7a19c0451334 # feat/T0003
