name: pr-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    uses: guilhermelinosp/templates/.github/workflows/shellcheck.yml@a841c2c75668b256587df5bd436ccc0fb917b6ee

  merge-check:
    uses: guilhermelinosp/templates/.github/workflows/merge-check.yml@dc560afab205e9571647b6757bdf31dedce39092

  gitleaks:
    uses: guilhermelinosp/templates/.github/workflows/gitleaks.yml@4e39ed05dca63221222868523e7e76fc02967713

  labeler:
    uses: guilhermelinosp/templates/.github/workflows/labeler.yml@1084fb26f3da3997992b2e8489928396030a5c3e

  go-quality:
    uses: guilhermelinosp/templates/.github/workflows/go-quality.yml@0d4b6ad86ea628e8cb377380c56fd4ffe4f0b28d
    with:
      go-version-file: go.mod
